name: Run Tests

on: [push]

jobs: 
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Run jest
        run: npm run test