name: Run Tests

on: [pull_request]

jobs: 
  run-test:
    permissions: 
      packages: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add credentials
        run: |-
          echo @space48:registry=https://npm.pkg.github.com/ >> .npmrc 
          echo //npm.pkg.github.com/:_authToken=${{ secrets.S48_NPM_TOKEN }}>> .npmrc
      - name: Install
        run: npm ci
      - name: Run jest
        run: npm run test